ContactsControl/Controllers/ContactController.cs
using ContactsControl.Filters;
using ContactsControl.Models;
using ContactsControl.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ContactsControl.Controllers
{
    [PaginaUsuarioLogado]
    public class ContactController : Controller
    {
        private readonly IContactRepository _contactRepository;
        public ContactController(IContactRepository contactRepository)
        {
            _contactRepository = contactRepository;
        }
        public IActionResult Index()
        {
            List<ContactModel> ContactList = _contactRepository.GetAllContacts();
            return View(ContactList);
        }
        public IActionResult CreateContact()
        {
            return View();
        }
        public IActionResult EditContact(int id)
        {
            ContactModel contato = _contactRepository.GetContact(id);
            return View(contato);
        }
        public IActionResult DeleteContact(int id)
        {
            Console.WriteLine("TELA DE EXCLUIR CADASTRO");
            ContactModel contato = _contactRepository.GetContact(id);
            return View(contato);
        }

        [HttpPost]
        public IActionResult CreateContact(ContactModel contato) 
        {
            try
            {
                if (ModelState.IsValid)//requisição banco só com dados do form validos
                {
                    _contactRepository.AddContact(contato);
                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso.";
                    return RedirectToAction("Index");
                }
                return View(contato); //se nao, retorna os dados que foram enviados
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Não conseguimos cadastrar o seu contato, tente novamente.\n" +
                    $"Detalhe do erro:{ex.Message}";
                return RedirectToAction("Index");
            }            
        }

        [HttpPost]
        public IActionResult AlterContact(ContactModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contactRepository.EditContact(contato);
                    TempData["MensagemSucesso"] = "Contato atualizado com sucesso.";
                    return RedirectToAction("Index");
                }
                return View("EditContact", contato);
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Não conseguimos atualizar o seu contato, tente novamente.\n" +
                    $"Detalhe do erro:{ex.Message}";
                return View("EditContact", contato); //ele irá voltar para a view 'AlterContact' que não existe, então forçamos a view que ele deve buscar
            }
        }

        public IActionResult ConfirmDeleteContact(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contactRepository.DeleteContact(id);
                    TempData["MensagemSucesso"] = "Contato excluído com sucesso.";
                    return RedirectToAction("Index");
                }
                ContactModel contato = _contactRepository.GetContact(id);
                return View(contato);
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Não conseguimos excluir o seu contato, tente novamente.\n" +
                    $"Detalhe do erro:{ex.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

ContactsControl/Controllers/UserController.cs
using ContactsControl.Filters;
using ContactsControl.Models;
using ContactsControl.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ContactsControl.Controllers
{
    [PaginaUsuarioAdminLogado]
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;
        public UserController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult Index()
        {
            List<UserModel> UserList = _userRepository.GetAllUsers();
            return View(UserList);
        }

        public IActionResult CreateUser()
        {
            return View();
        }

        public IActionResult EditUser(int id)
        {
            UserModel user = _userRepository.GetUser(id);
            return View(user);  
        }

        public IActionResult DeleteUser(int id)
        {
            Console.WriteLine("TELA DE EXCLUIR CADASTRO");
            UserModel user = _userRepository.GetUser(id);
            return View(user);
        }

        [HttpPost]
        public IActionResult CreateUser(UserModel user)
        {
            try
            {
                if (ModelState.IsValid)//requisição banco só com dados do form validos
                {
                    _userRepository.AddUser(user);
                    TempData["MensagemSucesso"] = "Usuário cadastrado com sucesso.";
                    return RedirectToAction("Index");
                }
                return View(user); //se nao, retorna os dados que foram enviados
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Não conseguimos cadastrar o usuário, tente novamente.\n" +
                    $"Detalhe do erro:{ex.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult AlterUser(EditUserModel userEdit)
        {
            try
            {
                UserModel user = null;

                if(ModelState.IsValid)
                {
                    user = new UserModel()
                    {
                        Id = userEdit.Id,
                        Nome = userEdit.Nome,
                        Login = userEdit.Login,
                        Email = userEdit.Email,
                        Perfil = userEdit.Perfil
                    };

                    user = _userRepository.EditUser(user);
                    TempData["MensagemSucesso"] = "Usuário atualizado com sucesso.";
                    return RedirectToAction("Index");
                }
                return View("EditUser", user);
            }
            catch(Exception ex)
            {
                TempData["MensagemErro"] = "Não conseguimos atualizar o seu contato, tente novamente.\n" +
                    $"Detalhe do erro:{ex.Message}";
                return View("Index"); //ele irá voltar para a view 'AlterContact' que não existe, então forçamos a view que ele deve buscar
            }
        }

        public IActionResult ConfirmDeleteUser(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _userRepository.DeleteUser(id);
                    TempData["MensagemSucesso"] = "Contato excluído com sucesso.";
                    return RedirectToAction("Index");
                }
                UserModel user = _userRepository.GetUser(id);
                return View(user);
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Não conseguimos excluir o usuário, tente novamente.\n" +
                    $"Detalhe do erro:{ex.Message}";
                return RedirectToAction("Index");
            }
        }

    }
}

ContactsControl/Views/User/CreateContact.cshtml
@model ContactModel
@{
    ViewData["Title"] = "Criar Contatos";
}
<div class="text-center">
    <h1 class="display-4">Cadastrar Contato</h1>
</div>


<form class="px-5" asp-controller="Contact" asp-action="CreateContact" method="post">
    <div class="container px-5">
        <div class="mb-3">
            <label for="Nome" class="form-label">Nome</label>
            <input type="text" class="form-control" asp-for="Name" placeholder="Digite o nome do contato">
            @Html.ValidationMessageFor(msg => msg.Name)
        </div>
        <div class="mb-3">
            <label for="Email" class="form-label">Email</label>
            <input type="email" class="form-control" asp-for="Email" placeholder="Digite o e-mail do contato">
            @Html.ValidationMessageFor(msg => msg.Email)
        </div>
        <div class="mb-3">
            <label for="Celular" class="form-label">Celular</label>
            <input type="text" class="form-control" asp-for="Celular" placeholder="Digite o celular do contato">
            @Html.ValidationMessageFor(msg => msg.Celular)
        </div>
        <div class="d-flex flex-column">
            <button type="submit" class="btn btn-primary btn-block mb-2">Cadastrar</button>
            <a class="btn btn-secondary btn-block" asp-controller="Contact" asp-action="Index">Voltar</a>
        </div>
    </div>
</form>

ContactsControl/Views/User/CreateUser.cshtml
@using ContactsControl.Enums;
@model UserModel
@{
    ViewData["Title"] = "Criar Usuários";
}
<div class="text-center">
    <h1 class="display-4">Cadastrar Usuário</h1>
</div>


<form class="px-5" asp-controller="User" asp-action="CreateUser" method="post">
    <div class="container px-5">
        <div class="mb-3">
            <label for="Nome" class="form-label">Nome</label>
            <input type="text" class="form-control" asp-for="Nome" placeholder="Digite o nome do usuário">
            @Html.ValidationMessageFor(msg => msg.Nome)
        </div>
        <div class="mb-3">
            <label for="Email" class="form-label">Email</label>
            <input type="email" class="form-control" asp-for="Email" placeholder="Digite o e-mail do usuário">
            @Html.ValidationMessageFor(msg => msg.Email)
        </div>
        <div class="mb-3">
            <label for="Perfil" class="form-label">Perfil</label>
            <select class="form-control" asp-for="Perfil"> @*asp-for => faz referencia a tabela nos models (banco de dados) *@
                <option value="">Selecione</option>
                <option value="@ProfileEnum.Admin">Administrador</option>
                <option value="@ProfileEnum.Padrao">Padrão</option>
            </select>
            @Html.ValidationMessageFor(msg => msg.Perfil)
        </div>
        <div class="mb-3">
            <label for="Celular" class="form-label">Login</label>
            <input type="text" class="form-control" asp-for="Login" placeholder="Digite o login do usuário">
            @Html.ValidationMessageFor(msg => msg.Login)
        </div>
        <div class="mb-3">
            <label for="Celular" class="form-label">Senha</label>
            <input type="password" class="form-control" asp-for="Senha" placeholder="Digite a senha do usuário">
            @Html.ValidationMessageFor(msg => msg.Senha)
        </div>

        <div class="d-flex flex-column">
            <button type="submit" class="btn btn-primary btn-block mb-2">Cadastrar</button>
            <a class="btn btn-secondary btn-block" asp-controller="Contact" asp-action="Index">Voltar</a>
        </div>
    </div>
</form>

ContactsControl/Views/User/DeleteUser.cshtml
@model UserModel
@{
    ViewData["Title"] = "Exclusão de Usuários";
}
<div class="text-center">
    <h3 class="display-4">Realmente deseja excluir o usuário: @Model.Nome ?</h3>
</div>

<div class="d-flex flex-column px-5">
    <a class="btn btn-primary mb-2" asp-controller="User" asp-action="ConfirmDeleteUser" asp-route-id="@Model.Id" role="button">Confirmar</a>
    <a class="btn btn-danger" asp-controller="User" asp-action="Index">Cancelar</a>
</div>

ContactsControl/Views/User/EditUser.cshtml
@using ContactsControl.Enums;
@model UserModel
@{
    ViewData["Title"] = "Editar Usuários";
}
<div class="text-center">
    <h1 class="display-4">Editar Usuário</h1>
</div>


<form class="px-5" asp-controller="User" asp-action="AlterUser" method="post">
        <div class="container px-5">
        <input type="hidden" asp-for="Id" />
        <div class="mb-3">
            <label for="Nome" class="form-label">Nome</label>@*asp-for já pega valor dos models, entao nao precisa do value no input*@
            <input type="text" class="form-control" asp-for="Nome" placeholder="Digite o nome do usuário" >
            @Html.ValidationMessageFor(msg => msg.Nome)
        </div>
        <div class="mb-3">
            <label for="Email" class="form-label">Email</label>
            <input type="email" class="form-control" asp-for="Email" placeholder="Digite o e-mail do usuário">
            @Html.ValidationMessageFor(msg => msg.Email)
        </div>
        <div class="mb-3">
            <label for="Celular" class="form-label">Login</label>
            <input type="text" class="form-control" asp-for="Login" placeholder="Digite o login do usuário">
            @Html.ValidationMessageFor(msg => msg.Login)
        </div>
        <div class="mb-3">
            <label for="Perfil" class="form-label">Perfil</label>
            <select class="form-control" asp-for="Perfil">
                @*asp-for => faz referencia a tabela nos models (banco de dados) *@
                <option value="">Selecione</option>
                <option value="@ProfileEnum.Admin">Administrador</option>
                <option value="@ProfileEnum.Padrao">Padrão</option>
            </select>
            @Html.ValidationMessageFor(msg => msg.Perfil)
        </div>

        <div class="d-flex flex-column">
            <button type="submit" class="btn btn-primary btn-block mb-2" >Atualizar</button>
            <a class="btn btn-secondary btn-block" asp-controller="User" asp-action="Index">Voltar</a>
        </div>
    </div>
</form>

ContactsControl/Views/User/Index.cshtml
@model List<UserModel>
@{
    ViewData["Title"] = "Lista de Usuários";
}


<div class="text-center">

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-success btn-sm close-alert">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <h1 class="display-4">Lista de Usuários</h1>
    <table class="table" id="table-usuarios">
        <thead>
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Nome</th>
                <th scope="col" class="text-center">Login</th>
                <th scope="col" class="text-center">E-mail</th>
                <th scope="col" class="text-center">Perfil</th>
                <th scope="col" class="text-center">Data de Cadastro</th>
                <th scope="col" class="text-center">
                    <div class="btn-group btn-wide" role="group">
                        <a class="btn btn-success px-lg-2" role="button" asp-controller="User" asp-action="CreateUser">Adicionar</a>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any())
            {
                foreach (UserModel user in Model)
                {
                    <tr>
                        <th scope="row" class="align-middle">@user.Id</th>
                        <td class="align-middle">@user.Nome</td>
                        <td class="align-middle">@user.Login</td>
                        <td class="align-middle">@user.Email</td>
                        <td class="align-middle">@(user.Perfil == ContactsControl.Enums.ProfileEnum.Admin ? "Administrador" : "Padrão")</td>
                        <td class="align-middle">@user.DataCadastro</td>
                        <td>
                            <div class="btn-group" role="group">
                                                                                @* passa a informação via rota *@
                                <a role="button" class="btn btn-primary" asp-route-id="@user.Id" asp-controller="User" asp-action="EditUser">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@user.Id" asp-controller="User" asp-action="DeleteUser"> Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top">Nenhum usuário encontrado</td></tr>
                @* <div class="text-center">
                    <span>Nenhum usuário encontrado</span>
                </div> *@
            }
        </tbody>
    </table>
</div>